[package]
name = "wallpaper"
version = "0.1.0"
authors = ["Gurtej Kanwar <gurtejkanwar@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
crate-type = ["cdylib"] # FORNOW: let's try loading in as dylib