[package]
name = "wallpaper"
version = "0.1.0"
authors = ["Gurtej Kanwar <gurtejkanwar@gmail.com>"]
edition = "2018"

[dependencies]
cty = "*"
kernel = { path = "../libkernel" }

[[bin]]
name = "wallpaper"
